### ISSUE TITLE
Issue with IDA Pro after installing the plugin

### ISSUE THREAD

**Issue by 0xcpu** [airbus-seclab/bincat#57] opened 2017-12-24 11:57 UTC
Hello,

I've installed the plugin on IDA Pro v7.0, after I've restarted IDA and loaded a binary(actually I tried many binaries), it gets into an unusable state and I consider that it's because of the plugin. Removing plugin's files does help, IDA starts again.

Here's a screenshot of the state IDA gets stuck after installing the plugin:
![issue](https://user-images.githubusercontent.com/2598963/34326317-121ac5a2-e8b2-11e7-8023-a648759701db.PNG)

System info:
`OS Name:                 Microsoft Windows 7 Ultimate
OS Version:                6.1.7601 Service Pack 1 Build 7601`
Plugin version:
`v0.8.1`

Thank you!

**Comment by trou** [comment] 2017-12-24 12:46
We've never run into such problem. Would you mind sharing an IDB ?

**Comment by ner0x652** [comment] 2017-12-24 19:13
I'm sorry, but it gets stuck before creating an IDB.

**Comment by trou** [comment] 2017-12-25 13:41
Do you have other plugins installed ? Are you running the 64 bits or 32 bits version ?

**Comment by ner0x652** [comment] 2017-12-25 16:04
Yes, I do have other plugins and I'm running the 32bit version. I'll try
running without other plugins and after, I'll let you know about the result.

**Comment by trou** [comment] 2018-01-01 11:29
Hello,
I'm thinking it could be related to http://www.hexblog.com/?p=1151 as we define quite a lot of variables, I would not be surprised if there was any naming conflict with another plugin.

**Comment by ner0x652** [comment] 2018-01-01 11:36
I've succeeded in starting it, even with other plugins and I don't have an
explanation of why it happened so. Now the problem is that it doesn't
close, it hangs during the closing stage(I mean IDA). That's very strange.

**Comment by trou** [comment] 2018-01-03 16:05
As the bug seems un reproducible, I'm closing the issue. Do not hesitate to reopen if you have more info.

**Comment by jthuraisamy** [comment] 2018-02-22 19:39
Hello, it does seem to be a conflict with another plugin. In my case it was [Lighthouse](https://github.com/gaasedelen/lighthouse). I tested this by removing all loaded third-party plugins, and then adding them back one-by-one.

@cpu-00, would you confirm if you also had Lighthouse loaded while using BinCAT?

**Comment by cpu-00** [comment] 2018-02-22 20:04
Yes, I confirm.

**Comment by trou** [comment] 2018-02-22 21:44
I'll try with lighthouse, thanks for the update

**Comment by trou** [comment] 2018-03-05 10:36
After investigating the problem with Hex-Rays support (thanks Arnaud !), it appears it was a problem in IDA.
The fix will be including in the next IDA release and can already be requested by users with a valid licence by mailing support@hex-rays.com.

Thanks everyone for the report !

**Closed by trou** 2018-03-05 10:36 UTC
Labels: IDA plugin
