### ISSUE TITLE
TypeError and AttributeError

### ISSUE THREAD

**Issue by PSR009** [airbus-seclab/bincat#111] opened 2020-06-05 12:42 UTC
Hi, I'm new to IDAPython. So, please help me out if it's resolved already or silly.

I've got the following issue while using `get_key_x86` example.
My environment is Ubuntu 18.04, with BinCAT v1.1 and:
```
Python 2.7.17
[GCC 7.5.0] 
IDAPython v7.4.0 final
```

When I launch BinCAT, it shows:
```bash
WARNING:bincat.gui.pluginoptions:IDAUSR not defined, using /home/user/.idapro
IDAPython: Error while calling Python callback <OnCreate>:
Traceback (most recent call last):
  File "/home/user/.idapro/plugins/idabincat/gui.py", line 1094, in OnCreate
    self.nextnodes_combo.currentTextChanged.connect(self.goto_next)
TypeError: connect() failed between currentTextChanged(QString) and goto_next()
IDAPython: Error while calling Python callback <OnCreate>:
Traceback (most recent call last):
  File "/home/user/.idapro/plugins/idabincat/gui.py", line 426, in OnCreate
    self.region_select.currentTextChanged.connect(self.update_region)
TypeError: connect() failed between currentTextChanged(QString) and update_region()
IDAPython: Error while calling Python callback <OnCreate>:
Traceback (most recent call last):
  File "/home/user/.idapro/plugins/idabincat/gui.py", line 599, in OnCreate
    self.cfg_select.currentIndexChanged.connect(self._load_config)
TypeError: decorated slot has no signature compatible with currentIndexChanged(int)
INFO:bincat.plugin:IDABinCAT ready.
```

and when I click on `IDA View-A` tab, it says:
```bash
Exception in ida_kernwin.UI_Hooks dispatcher function: SWIG director method error. Error detected when calling 'UI_Hooks.updating_actions'
Traceback (most recent call last):
  File "/home/user/.idapro/plugins/idabincat/gui.py", line 2164, in updating_actions
    self.s.set_current_ea(ea)
  File "/home/user/.idapro/plugins/bcplugin.py", line 729, in set_current_ea
    self.gui.after_change_ea()
  File "/home/user/.idapro/plugins/idabincat/gui.py", line 2288, in after_change_ea
    self.BinCATRegistersForm.update_current_ea(self.s.current_ea)
  File "/home/user/.idapro/plugins/idabincat/gui.py", line 1244, in update_current_ea
    self.node_select.blockSignals(True)
AttributeError: 'BinCATRegistersForm_t' object has no attribute 'node_select'
```

and when I try to analyse, it says:
```bash
INFO:bincat.gui:Launching the analyzer
Traceback (most recent call last):
  File "/home/user/.idapro/plugins/idabincat/gui.py", line 1986, in activate
    self.s.gui.BinCATConfigForm.launch_analysis()
  File "/home/user/.idapro/plugins/idabincat/gui.py", line 795, in launch_analysis
    self._update_edit_config()
  File "/home/user/.idapro/plugins/idabincat/gui.py", line 777, in _update_edit_config
    start_addr = int(self.ip_start_addr.text(), 16)
AttributeError: 'BinCATConfigForm_t' object has no attribute 'ip_start_addr'
```
I've turned the compatibility layer ON and tried using Python 3.6.9 too but no luck.

Thanks!

**Comment by trou** [comment] 2020-06-16 15:59
Hello,
sorry I haven't had time to look at it. Can you please try with the latest master build ? You can download it here : https://dev.azure.com/airbus-seclab/bincat/_build

**Comment by trou** [comment] 2021-11-24 13:35
Thanks for the report. Since I could not reproduce using a recent IDA version, and as support for Python 2.7 has been deprecated, I'm closing the bug.

**Closed by trou** 2021-11-24 13:35 UTC
