### ISSUE TITLE
"BinCAT -> Analyze from here": throwing syntax error message

### ISSUE THREAD

**Issue by k1p0d** [airbus-seclab/bincat#124] opened 2021-04-11 12:26 UTC
**Environment:** 

- Host: Windows 10
- IDA ver: 7.6 
- Sample: ARMv7 / Linux

**Whats wrong?**

Hey when clicking on "BinCAT-> Analyze from here" 
I get in the output window - 

---

WARNING:bincat.gui.pluginoptions:IDAUSR not defined, using C:\Users\XXX\AppData\Roaming\Hex-Rays\IDA Pro
INFO:bincat.plugin:IDABinCAT ready.
INFO:bincat.gui:Launching the analyzer
INFO:bincat.plugin:Current analyzer path: C:\Users\XXX\AppData\Local\Temp\tmpxmalk2b4bincat
ERROR:bincat.plugin.npkgen:Error encountered while running gcc. Is it installed in PATH?
WARNING:bincat.plugin:Could not compile header file, types from IDB will not be used for type propagation
WARNING:bincat.plugin:.no file containing type data for the file being analyzed could not be generated, continuing. The ida-generated header could be invalid.
INFO:bincat.plugin:Analyzer: starting process
INFO:bincat.plugin:Analyzer started.
INFO:bincat.plugin:Analyzer process finished
ERROR:bincat.plugin:analyzer returned exit code=2
INFO:bincat.plugin:---- stdout ----------------
INFO:bincat.plugin:b'BinCAT v1.1-dirty\r\n'
INFO:bincat.plugin:---- stderr ----------------
INFO:bincat.plugin:b'EXCEPTION: Exceptions.Error("Syntax error near location (101, 14) of C:\\\\Users\\\\XXX\\\\AppData\\\\Local\\\\Temp\\\\tmpxmalk2b4bincat\\\\init.ini")\r\nCheck log file for details [C:\\Users\\XXX\\AppData\\Local\\Temp\\tmpxmalk2b4bincat\\analyzer.log]\r\n'
INFO:bincat.plugin:---- logfile ---------------
INFO:bincat.plugin:[INFO]  main: BinCAT version v1.1-dirty
INFO:bincat.plugin:[ABORT] main: Syntax error near location (101, 14) of C:\Users\XXX\AppData\Local\Temp\tmpxmalk2b4bincat\init.ini
INFO:bincat.plugin:Raised by primitive operation at file "utils/log.ml", line 157, characters 41-69
INFO:bincat.plugin:Called from file "main.ml", line 64, characters 8-105
INFO:bincat.plugin:Called from file "bincat.ml", line 42, characters 7-49
INFO:bincat.plugin:[EXCEPTION] main: Exception caught in main loop
INFO:bincat.plugin:Exceptions.Error("Syntax error near location (101, 14) of C:\\Users\\XXX\\AppData\\Local\\Temp\\tmpxmalk2b4bincat\\init.ini")
INFO:bincat.plugin:Raised at file "utils/log.ml", line 160, characters 4-32
INFO:bincat.plugin:Called from file "main.ml", line 64, characters 8-105
INFO:bincat.plugin:[STOP] nothing analyzed
INFO:bincat.plugin:====== end of logfile ======
ERROR:bincat.plugin:Could not parse result file

---

saying this file C:\Users\XXX\AppData\Local\Temp\tmptul3b3p4bincat\init.ini contains a syntax error at (101, 14)
which contains the following line - 

`remap_binary = False`

any ideas ?

**Comment by trou** [comment] 2021-04-13 07:14
Which version are you running? Are you sure the IDA plugin and analyzer are in sync ?

**Comment by trou** [comment] 2021-11-24 13:42
I cannot reproduce, closing.

**Closed by trou** 2021-11-24 13:42 UTC
